/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import Controller.FunctionHandler;
import Model.BrowesFile;
import Model.KidExl;
import Model.KidFinal;
import Model.KidTxt;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import jxl.write.WriteException;

/**
 *
 * @author Paaske
 */
public class MainViewV2 extends BrowesFile {

    /**
     * Creates new form MainView
     */
    public MainViewV2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        btn_Browse_txt = new javax.swing.JButton();
        tf_Browse_txt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_Browse_Excel = new javax.swing.JTextField();
        btn_Browse_Excel = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        tf_FileName = new javax.swing.JTextField();
        btn_SaveFile = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lbl_Status = new javax.swing.JLabel();
        lbl_Status2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        tf_FileName1 = new javax.swing.JTextField();
        btn_SaveFile1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lbl_Status1 = new javax.swing.JLabel();
        lbl_Status3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KlubMix List Merger");

        btn_Browse_txt.setText("Browse");
        btn_Browse_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Browse_txtMouseClicked(evt);
            }
        });

        tf_Browse_txt.setText("Browse Txt");
        tf_Browse_txt.setMaximumSize(new java.awt.Dimension(108, 20));
        tf_Browse_txt.setMinimumSize(new java.awt.Dimension(108, 20));
        tf_Browse_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_Browse_txtMouseClicked(evt);
            }
        });

        jLabel1.setText("Browse for Text File (.txt)");

        jLabel2.setText("Browse for Excel File (.xls)");

        tf_Browse_Excel.setText("Browse Excel");
        tf_Browse_Excel.setMaximumSize(new java.awt.Dimension(108, 20));
        tf_Browse_Excel.setMinimumSize(new java.awt.Dimension(108, 20));
        tf_Browse_Excel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_Browse_ExcelMouseClicked(evt);
            }
        });

        btn_Browse_Excel.setText("Browse");
        btn_Browse_Excel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Browse_ExcelMouseClicked(evt);
            }
        });

        tf_FileName.setText("FileName");
        tf_FileName.setMaximumSize(new java.awt.Dimension(108, 20));
        tf_FileName.setMinimumSize(new java.awt.Dimension(108, 20));
        tf_FileName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_FileNameFocusGained(evt);
            }
        });
        tf_FileName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_FileNameKeyPressed(evt);
            }
        });

        btn_SaveFile.setText("Save");
        btn_SaveFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_SaveFileMouseClicked(evt);
            }
        });

        jLabel4.setText("Status :");

        lbl_Status.setText("Ready");

        lbl_Status2.setText("      ");

        jLabel3.setText("Save Excel File");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tf_FileName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_SaveFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_Status2)
                            .addComponent(lbl_Status))))
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_FileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_SaveFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lbl_Status))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Status2)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Tabelex", jPanel1);

        tf_FileName1.setText("FileName");
        tf_FileName1.setMaximumSize(new java.awt.Dimension(108, 20));
        tf_FileName1.setMinimumSize(new java.awt.Dimension(108, 20));
        tf_FileName1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_FileName1FocusGained(evt);
            }
        });
        tf_FileName1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_FileName1KeyPressed(evt);
            }
        });

        btn_SaveFile1.setText("Save");
        btn_SaveFile1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_SaveFile1MouseClicked(evt);
            }
        });

        jLabel5.setText("Status :");

        lbl_Status1.setText("Ready");

        lbl_Status3.setText("      ");

        jLabel6.setText("Save Excel File");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tf_FileName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_SaveFile1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_Status3)
                            .addComponent(lbl_Status1))))
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_FileName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_SaveFile1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbl_Status1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Status3)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Trafiklys", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tf_Browse_Excel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_Browse_txt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_Browse_txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Browse_Excel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Browse_txt)
                    .addComponent(tf_Browse_txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_Browse_Excel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Browse_Excel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Browse_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Browse_txtMouseClicked
        tf_Browse_txt.setText(selectTxt());
    }//GEN-LAST:event_btn_Browse_txtMouseClicked

    private void btn_Browse_ExcelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Browse_ExcelMouseClicked
        tf_Browse_Excel.setText(selectExcel());
    }//GEN-LAST:event_btn_Browse_ExcelMouseClicked

    private void btn_SaveFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SaveFileMouseClicked
        createExcel();

    }//GEN-LAST:event_btn_SaveFileMouseClicked

    private void createExcel() throws HeadlessException {
        String tf_Txt_Path, tf_Excel_Path, tf_Fname;
        tf_Txt_Path = tf_Browse_txt.getText();
        tf_Excel_Path = tf_Browse_Excel.getText();
        tf_Fname = tf_FileName.getText();
        FunctionHandler fHandler = new FunctionHandler();
        ArrayList<KidTxt> tabelexList = new ArrayList<>();
        try {
            if (!"Browse Txt".equals(tf_Txt_Path) && !"No File Selected".equals(tf_Txt_Path)) {
                tabelexList = fHandler.readTxt(tf_Txt_Path);
                if (!tabelexList.isEmpty()) {
                    lbl_Status.setText("Tablet Kids : " + String.valueOf(tabelexList.size()));
                }
                
                if (!"Browse Excel".equals(tf_Excel_Path) && !"No File Selected".equals(tf_Excel_Path)) {
                    ArrayList<KidExl> kidXl = fHandler.readXls(tf_Excel_Path);
                    if (!kidXl.isEmpty()) {
                        lbl_Status2.setText("Excel Kids : " + String.valueOf(kidXl.size()));
                    }
                    
//                    ArrayList<KidFinal> finKidList = fHandler.mergeToList(tabelexList, kidXl);
//                    boolean isSuccess = fHandler.createExcelFile(finKidList, tf_Fname);
//                    
//                    if (isSuccess == true) {
//                        JOptionPane.showMessageDialog(rootPane, "A file named " + tf_Fname + ".xls was created on the desktop");
//                    } else {
//                        JOptionPane.showMessageDialog(rootPane, "Something went wrong.");
//                    }
                } else {
                    tf_Browse_Excel.setText("No File Selected");
                }
                
            } else {
                tf_Browse_txt.setText("No File Selected");
                tf_Browse_Excel.setText("No File Selected");
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainViewV2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void tf_Browse_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_Browse_txtMouseClicked
        tf_Browse_txt.setText(selectTxt());
    }//GEN-LAST:event_tf_Browse_txtMouseClicked

    private void tf_Browse_ExcelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_Browse_ExcelMouseClicked
        tf_Browse_Excel.setText(selectExcel());
    }//GEN-LAST:event_tf_Browse_ExcelMouseClicked

    private void tf_FileNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_FileNameFocusGained
        tf_FileName.selectAll();
    }//GEN-LAST:event_tf_FileNameFocusGained

    private void tf_FileNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_FileNameKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) createExcel();
    }//GEN-LAST:event_tf_FileNameKeyPressed

    private void tf_FileName1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_FileName1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_FileName1FocusGained

    private void tf_FileName1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_FileName1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_FileName1KeyPressed

    private void btn_SaveFile1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SaveFile1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_SaveFile1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainViewV2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainViewV2().setVisible(true);
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Browse_Excel;
    private javax.swing.JButton btn_Browse_txt;
    private javax.swing.JButton btn_SaveFile;
    private javax.swing.JButton btn_SaveFile1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lbl_Status;
    private javax.swing.JLabel lbl_Status1;
    private javax.swing.JLabel lbl_Status2;
    private javax.swing.JLabel lbl_Status3;
    private javax.swing.JTextField tf_Browse_Excel;
    private javax.swing.JTextField tf_Browse_txt;
    private javax.swing.JTextField tf_FileName;
    private javax.swing.JTextField tf_FileName1;
    // End of variables declaration//GEN-END:variables
}
